ginkgo: force non-ab update package
AssertionError: META/ab_partitions.txt is required for ab_update.

Signed-off-by: Joe7500 <j7545032@gmail.com>
Signed-off-by: Edwiin Kusuma Jaya <kutemeikito0905@gmail.com>
Signed-off-by: Miracleprjkt <Miraclev1@proton.me>